// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPKomM2lVZjc59T-R8ORBF423vXlOE5k',
    appId: '1:374238627315:web:5aa709c1eec0fda4543e86',
    messagingSenderId: '374238627315',
    projectId: 'act12-b48e7',
    authDomain: 'act12-b48e7.firebaseapp.com',
    storageBucket: 'act12-b48e7.firebasestorage.app',
    measurementId: 'G-842NR3Z85V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEib0_T_1Jzura1H-9G3POamL3Eo04pjA',
    appId: '1:374238627315:android:317db2289389d9fa543e86',
    messagingSenderId: '374238627315',
    projectId: 'act12-b48e7',
    storageBucket: 'act12-b48e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19QOhE30jjfqEtCJFkHH8kgBKxM8cqNE',
    appId: '1:374238627315:ios:ad46cdcc3a137bb8543e86',
    messagingSenderId: '374238627315',
    projectId: 'act12-b48e7',
    storageBucket: 'act12-b48e7.firebasestorage.app',
    iosBundleId: 'com.example.ca12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD19QOhE30jjfqEtCJFkHH8kgBKxM8cqNE',
    appId: '1:374238627315:ios:ad46cdcc3a137bb8543e86',
    messagingSenderId: '374238627315',
    projectId: 'act12-b48e7',
    storageBucket: 'act12-b48e7.firebasestorage.app',
    iosBundleId: 'com.example.ca12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAPKomM2lVZjc59T-R8ORBF423vXlOE5k',
    appId: '1:374238627315:web:ec283e49885dd143543e86',
    messagingSenderId: '374238627315',
    projectId: 'act12-b48e7',
    authDomain: 'act12-b48e7.firebaseapp.com',
    storageBucket: 'act12-b48e7.firebasestorage.app',
    measurementId: 'G-MXDSSY5NQN',
  );
}
